// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfyo_h_CWlXyuL_yUk_y9xQvWWKV1iErY',
    appId: '1:620365827964:android:4f27e5c196fccb8e0a9ef9',
    messagingSenderId: '620365827964',
    projectId: 'ulearning-app-a3f53',
    storageBucket: 'ulearning-app-a3f53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN3Bn7BiNKQUqVCyVAyxo54Lm8B_Bv6yo',
    appId: '1:620365827964:ios:33645e06881ba4b20a9ef9',
    messagingSenderId: '620365827964',
    projectId: 'ulearning-app-a3f53',
    storageBucket: 'ulearning-app-a3f53.firebasestorage.app',
    iosBundleId: 'com.example.riverpodProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN3Bn7BiNKQUqVCyVAyxo54Lm8B_Bv6yo',
    appId: '1:620365827964:ios:33645e06881ba4b20a9ef9',
    messagingSenderId: '620365827964',
    projectId: 'ulearning-app-a3f53',
    storageBucket: 'ulearning-app-a3f53.firebasestorage.app',
    iosBundleId: 'com.example.riverpodProject',
  );

}